# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftHuoHua' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # 网络请求库
  pod 'Moya'
  # 加载指示器库
  pod 'MBProgressHUD'
  # json解析库
  pod 'SwiftyJSON'
  pod 'HandyJSON'
end
