# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftHuoHua' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # 网络请求库
  pod 'Moya'
  # 加载指示器库
  pod 'MBProgressHUD'
  # json解析库
  pod 'SwiftyJSON'
  pod 'HandyJSON'
  # ui 约束
  pod 'SnapKitExtend'
  # 刷新库
  pod 'MJRefresh'
  # 网络图片加载库
  pod 'Kingfisher'
  # 轮播图库
  pod 'LLCycleScrollView'
  # 分段控制器三方库
  pod 'HMSegmentedControl'
  # swift初始化库 Then
  pod 'Then'
  # swift三方数据库
  pod 'RealmSwift'
  pod 'Realm'
  
end
